# Generated by Django 5.2.9 on 2026-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_teammember_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
